[build]
  publish = "."
  command = "echo 'No build needed' "

[[edge_functions]]
  function = "analyze"
  path = "/api/analyze"

[template.environment]
  OPENAI_API_KEY = "Set your OpenAI API key here"
